### PR TITLE
fix: fail gracefully on private non pro

### LINKED ISSUE #401: 🚀 Feature: Fail setup more gracefully for branch protections on private, non-Pro repos
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Forking from #398: apparently you must have GitHub Pro to set branch protections on a private repo. TIL. Right now the setup script fails with:

```plaintext

◇  ❌ Error hydrating initial repository settings.
│
└  Looks like there was a problem. Correct it and try again? 😕


Error: Could not hydrate initial repository settings. 
    at withSpinner (file:///Users/josh/repos/testing-private-repo/script/setup.js:166:10)
    at async file:///Users/josh/repos/testing-private-repo/script/setup.js:430:3 {
  [cause]: RequestError [HttpError]: Not Found
      at /Users/josh/repos/testing-private-repo/node_modules/.pnpm/@octokit+request@6.2.3/node_modules/@octokit/request/dist-node/index.js:78:21
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async requestWithGraphqlErrorHandling (/Users/josh/repos/testing-private-repo/node_modules/.pnpm/@octokit+plugin-retry@4.1.3_@octokit+core@4.1.0/node_modules/@octokit/plugin-retry/dist-node/index.js:42:20)
      at async Job.doExecute (/Users/josh/repos/testing-private-repo/node_modules/.pnpm/bottleneck@2.19.5/node_modules/bottleneck/light.js:405:18) {
    status: 404,
    response: {
      url: 'https://api.github.com/repos/asdf/testing-private-repo',
      status: 404,
      headers: [Object],
      data: [Object]
    },
    request: {
      method: 'PATCH',
      url: 'https://api.github.com/repos/asdf/testing-private-repo',
      headers: [Object],
      body: '{"allow_auto_merge":true,"allow_rebase_merge":false,"allow_squash_merge":true,"default_branch":"main","delete_branch_on_merge":true,"description":"asdf","has_wiki":false}',
      request: [Object]
    }
  }
}
```

...so much noise! And there's really no need to cancel the rest of setup & mark the whole thing as failed.

Instead, let's mention the error and continue gracefully. How about something like...

```plaintext

◇  ✅ Hydrated initial repository settings.
│
◇  ⚠️ Could not hydrate branch protection settings: private repositories require GitHub Pro for that API.
│
◇  ✅ Finished API hydration.
```

(that's just a starting suggestion I haven't put much thought into - please improve it if you have any ideas!)

### Additional Info

To get this complaint:

1. Fork this template into a new private repo on GitHub
2. Clone that repo locally
3. `pnpm install`
4. `pnpm run setup`

### PR DESCRIPTION
**Pull request by RNR1**
## PR Checklist

- [x] Addresses an existing open issue: fixes #401 
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Fail gracefully for branch protection settings for private repos (non-Pro).
- Added `warnText` field to the "withSpinner" options
- `withSpinner` will now store its callback return value, and will show `warnText` in case the value is `false`

Bonus: I changed all the `catch (err)` to `catch (error)` just for consistency (git blame on me)

I'm honestly not so excited about this solution, but submitting it anyway to hear your thoughts

### CODE REVIEW

File: script/setup.js [hunk 1]
```diff
@@ -275,7 +275,7 @@ try {
 			let user;
 			try {
 				user = JSON.parse((await $`gh api user`).stdout).login;
-			} catch (err) {
+			} catch (error) {
```
Comment (JoshuaKGoldberg) [inline script/setup.js:278]: Oh, heh, this is unused... +1 to calling it `error` over `err`. I suppose we should enable https://eslint.org/docs/latest/rules/no-unused-vars#caughterrors...

Comment (JoshuaKGoldberg) [reply script/setup.js:278]: #426

**Review by JoshuaKGoldberg — APPROVED** [review]
💯, this is excellent. Tried it out locally and it works great. Thanks @RNR1!

Returning `false` makes sense to me - we can always rethink later if it gets more convoluted over time.

Note that I filed #425 around curly styles as a followup. I prefer brackets always for consistency. So I'll do that myself 😄

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @RNR1 for design
